# Generated by Django 3.1.3 on 2020-11-11 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('verfied', models.IntegerField(blank=True, null=True)),
                ('geo', models.TextField(blank=True, null=True)),
                ('quoted', models.BigIntegerField(blank=True, null=True)),
                ('favorite', models.BigIntegerField(blank=True, null=True)),
                ('retweet', models.BigIntegerField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('media_type', models.TextField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('media_id', models.FloatField(blank=True, null=True)),
                ('rt', models.IntegerField(blank=True, null=True)),
                ('rt_username', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('typeOrg', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=50)),
                ('joining_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 11, 11, 20, 42, 36, 931921))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('twitter_user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(default=None)),
                ('otp', models.CharField(max_length=10)),
                ('otp_time_stamp', models.DateTimeField(default=datetime.datetime(2020, 11, 11, 20, 42, 36, 929927))),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User_Organisation_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.organisations')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet_Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=150)),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.data')),
            ],
        ),
        migrations.CreateModel(
            name='Topic_Tweet_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.topics')),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.data')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('initiated_at', models.DateTimeField(default=datetime.datetime(2020, 11, 11, 20, 42, 36, 932918))),
                ('decision_passed_at', models.DateTimeField(default=datetime.datetime(2020, 11, 11, 20, 42, 36, 932918))),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.organisations')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.topics')),
            ],
        ),
        migrations.CreateModel(
            name='POC_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_details', models.TextField(default=None)),
                ('is_approved', models.BooleanField(default=False)),
                ('decision_passed_at', models.DateTimeField(default=datetime.datetime(2020, 11, 11, 20, 42, 36, 933916))),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.user')),
            ],
        ),
        migrations.AddField(
            model_name='organisations',
            name='POC_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.user'),
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate', models.TextField(default=None)),
                ('donated_at', models.DateTimeField(default=datetime.datetime(2020, 11, 11, 20, 42, 36, 932918))),
                ('is_complete', models.BooleanField(default=False)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.request')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.user')),
            ],
        ),
    ]
