# Generated by Django 3.1.3 on 2020-11-11 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soulage', '0003_auto_20201111_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Collection',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('verfied', models.IntegerField(blank=True, null=True)),
                ('geo', models.TextField(blank=True, null=True)),
                ('quoted', models.BigIntegerField(blank=True, null=True)),
                ('favorite', models.BigIntegerField(blank=True, null=True)),
                ('retweet', models.BigIntegerField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('media_type', models.TextField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('media_id', models.FloatField(blank=True, null=True)),
                ('rt', models.IntegerField(blank=True, null=True)),
                ('rt_username', models.TextField(blank=True, null=True)),
                ('stored_at', models.DateTimeField(default=datetime.datetime(2020, 11, 11, 21, 1, 9, 237018))),
            ],
        ),
        migrations.AlterField(
            model_name='donations',
            name='donated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 21, 1, 9, 243001)),
        ),
        migrations.AlterField(
            model_name='poc_requests',
            name='decision_passed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 21, 1, 9, 243997)),
        ),
        migrations.AlterField(
            model_name='request',
            name='decision_passed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 21, 1, 9, 242005)),
        ),
        migrations.AlterField(
            model_name='request',
            name='initiated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 21, 1, 9, 242005)),
        ),
        migrations.AlterField(
            model_name='topics',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 21, 1, 9, 240008)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 21, 1, 9, 238015)),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 21, 1, 9, 238015)),
        ),
        migrations.AlterField(
            model_name='topic_tweet_map',
            name='tweet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.data_collection'),
        ),
        migrations.AlterField(
            model_name='tweet_sentiment',
            name='tweet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soulage.data_collection'),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
