# Generated by Django 3.0 on 2021-03-18 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soulage', '0012_auto_20210318_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc_requests',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data_collection',
            name='stored_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 22, 42, 59, 40984)),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 22, 42, 59, 47967)),
        ),
        migrations.AlterField(
            model_name='poc_requests',
            name='decision_passed_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 22, 42, 59, 48964)),
        ),
        migrations.AlterField(
            model_name='poc_requests',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 22, 42, 59, 48964)),
        ),
        migrations.AlterField(
            model_name='request',
            name='decision_passed_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 22, 42, 59, 47967)),
        ),
        migrations.AlterField(
            model_name='request',
            name='initiated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 22, 42, 59, 47967)),
        ),
        migrations.AlterField(
            model_name='topics',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 22, 42, 59, 44974)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 22, 42, 59, 42979)),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 22, 42, 59, 42979)),
        ),
    ]
